services:
  app:
    profiles:
      - app-image
    build: .
    container_name: style-ai-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - YOURAPP_DB_HOST=${DB_HOST}
      - YOURAPP_DB_PORT=${DB_PORT}
      - YOURAPP_DB_NAME=${DB_NAME}
      - YOURAPP_DB_USER=${DB_USER}
      - YOURAPP_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8081/realms/style-ai
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - style-ai-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: style-ai-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8081
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - style-ai-net

  postgres:
    image: postgres:16-alpine
    container_name: style-ai-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME},keycloak
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - style-ai-net

  redis:
    image: redis:7-alpine
    container_name: style-ai-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - style-ai-net

networks:
  style-ai-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
