services:
  app:
    profiles:
      - app-image
    build: .
    container_name: style-ai-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - YOURAPP_DB_HOST=${DB_HOST}
      - YOURAPP_DB_PORT=${DB_PORT}
      - YOURAPP_DB_NAME=${DB_NAME}
      - YOURAPP_DB_USER=${DB_USER}
      - YOURAPP_DB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8081/realms/style-ai
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - style-ai-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: style-ai-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - style-ai-net

  postgres:
    image: postgres:16-alpine
    container_name: style-ai-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME},keycloak
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - style-ai-net

  redis:
    image: redis:7-alpine
    container_name: style-ai-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - style-ai-net

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: style-ai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - style-ai-net

  grafana:
    image: grafana/grafana:10.0.3
    container_name: style-ai-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - style-ai-net

networks:
  style-ai-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  grafana_data:
